-- Enforce per-user isolation on the 'images' storage bucket.
-- This ensures that even if application logic fails, a user
-- cannot access another user's files.

-- 1. Enable Row Level Security on the storage.objects table.
--    This table holds metadata for all files in all buckets.
alter table storage.objects enable row level security;

-- 2. Create a policy that allows access only if the file path
--    starts with 'protected/<user-id>/'. This matches the path
--    format generated by the `imagePathFor` helper.
--    This policy applies to ALL actions (SELECT, INSERT, UPDATE, DELETE).
create policy "Image owner can access their own protected files"
  on storage.objects for all
  using (
    bucket_id = 'images' and
    starts_with(name, 'protected/' || auth.uid()::text || '/')
  );
